name: dds-project

services:
  byzantine:
    build:
      context: .
    deploy:
      mode: replicated
      replicas: ${DDS_NUM_BYZ}
    env_file: '.env'
    environment:
      DDS_IS_BYZANTINE: true
    networks:
      - standard
    user: 1000:1000
  node:
    build:
      context: .
    depends_on:
      byzantine:
        condition: service_started
        required: true
    deploy:
      mode: replicated
      replicas: ${DDS_NUM_CORRECT}
    env_file: '.env'
    environment:
      DDS_IS_BYZANTINE: false
    networks:
      - standard
    user: 1000:1000


networks:
  standard:
    enable_ipv6: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: ${DDS_NETWORK}
          ip_range: ${DDS_NETWORK}
    name: 'standard'
