name: dds-project

services:
  node:
    build:
      context: .
    deploy:
      mode: replicated
      replicas: ${DDS_NUM_HOSTS}
    env_file: '.env'
    networks:
      - standard
    user: 1000:1000

networks:
  standard:
    enable_ipv6: false
    internal: true
    ipam:
      driver: default
      config:
        - subnet: ${DDS_NETWORK}
          ip_range: ${DDS_NETWORK}
    name: 'standard'
